/*
 * May 10th, 2020
 * Erika Graham
 * Algorith Design
 */

/**
 *
 * @author kikag
 */
public class FrmAlgorithmDesign extends javax.swing.JFrame {

    /**
     * Creates new form FrmAlgorithmDesign
     */
    public FrmAlgorithmDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblInstructionsFactorial = new javax.swing.JLabel();
        lblInstructionsPrime = new javax.swing.JLabel();
        lblInstructionsFibonacci = new javax.swing.JLabel();
        txtFactorial = new javax.swing.JTextField();
        txtPrime = new javax.swing.JTextField();
        txtFibonacci = new javax.swing.JTextField();
        btnFactorial = new javax.swing.JButton();
        btnPrime = new javax.swing.JButton();
        btnFibonacci = new javax.swing.JButton();
        lblFactorial = new javax.swing.JLabel();
        lblPrime = new javax.swing.JLabel();
        lblFibonacci = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitle.setText("+++Algorithm Design+++");

        lblInstructionsFactorial.setText("Enter a number and click the button to find the factorial:");

        lblInstructionsPrime.setText("Enter a number and click the button to determine whether or not it is a prime number: ");

        lblInstructionsFibonacci.setText("Enter a number and click the button to see the corresponding Fibonacci number:");

        btnFactorial.setText("Factorial");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnPrime.setText("Prime");
        btnPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeActionPerformed(evt);
            }
        });

        btnFibonacci.setText("Fibonacci");
        btnFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibonacciActionPerformed(evt);
            }
        });

        lblFactorial.setText("...");

        lblPrime.setText("...");

        lblFibonacci.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstructionsPrime)
                            .addComponent(lblInstructionsFactorial)
                            .addComponent(lblInstructionsFibonacci)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFibonacci)
                                    .addComponent(btnFactorial)
                                    .addComponent(btnPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFibonacci)
                                    .addComponent(lblPrime)
                                    .addComponent(lblFactorial)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lblTitle)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(45, 45, 45)
                .addComponent(lblInstructionsFactorial)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial)
                    .addComponent(lblFactorial))
                .addGap(41, 41, 41)
                .addComponent(lblInstructionsPrime)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrime)
                    .addComponent(lblPrime))
                .addGap(34, 34, 34)
                .addComponent(lblInstructionsFibonacci)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFibonacci)
                    .addComponent(lblFibonacci))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean primeNum (int n1){
        
        int prime = n1;     //declared variables
        int result;
        boolean flag = true;
        //for loop to identify how many times the number can be divided by 2
        for (int i = 2; i <= prime / 2; ++i) {
            
            result = prime % i;
            
            if (result == 0) //condition for nonprime numbers
            {
                flag = false;
                break;
            }
        }
        // print result to user
        return flag;
    }
    
    public int factorialResult (int n1){
        
        int factorial = n1;
        
        for (int i = factorial - 1; i >= 1; i = i - 1) {
            factorial = factorial * i;
        }
        return factorial;
    }
    
    public int fibonacciNum (int n1){
        
        int n = n1;
        //recursive formula
        int t1 = 1; int t2 = 1; int tn=0; int tnM1; int tnM2;
        
        for(int i=3;i<=n;i++){
            tn = t1 + t2;
            t1 = t2;
            t2 = tn;
            
        }
        return tn;
    }
    
    private void btnPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeActionPerformed
        //get number from the user and parse it to an integer
        int checkPrime = Integer.parseInt(txtPrime.getText());
        
        //call method to check whether it's a prime number or not
        if (primeNum(checkPrime)==true){
            lblPrime.setText(checkPrime+" is a prime number.");
            
        } else if (primeNum(checkPrime)==false){
            lblPrime.setText(checkPrime + " is not a prime number.");
        }
        
    }//GEN-LAST:event_btnPrimeActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        //get user's input
        int inputfactorial = Integer.parseInt(txtFactorial.getText());
        //get method's result
        int result = factorialResult(inputfactorial);
        //display result to user
        lblFactorial.setText(String.valueOf(result));
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibonacciActionPerformed
        // get position of the number from the user
        int fibonacciInput = Integer.parseInt(txtFibonacci.getText());
        //get method'd result
        int number = fibonacciNum(fibonacciInput);
        //display result to user
        lblFibonacci.setText(String.valueOf(number));
    }//GEN-LAST:event_btnFibonacciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlgorithmDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFibonacci;
    private javax.swing.JButton btnPrime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFactorial;
    private javax.swing.JLabel lblFibonacci;
    private javax.swing.JLabel lblInstructionsFactorial;
    private javax.swing.JLabel lblInstructionsFibonacci;
    private javax.swing.JLabel lblInstructionsPrime;
    private javax.swing.JLabel lblPrime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFactorial;
    private javax.swing.JTextField txtFibonacci;
    private javax.swing.JTextField txtPrime;
    // End of variables declaration//GEN-END:variables
}
